### ISSUE TITLE
Does not support `module.rules` syntax

### ISSUE THREAD

**Issue by ahamid** [vandy/webpack-babel-external-helpers-2#3]
This plugin does not appear to support the WebPack 2+ `module.rules` syntax, and will do nothing (or throw an error if `{strict: true}` option is set):

https://github.com/vandy/webpack-babel-external-helpers-2/blob/master/src/webpack-modification/configuration/loaders.js#L21

**Comment by vandy** [comment]
`module.rules` are now supported in 2.x version.
