### ISSUE TITLE
Support WebPack 3

### ISSUE THREAD

**Issue by ahamid** [vandy/webpack-babel-external-helpers-2#4]
A WebPack API changed to a class:

```
SingleEntryDependency.call(this, request);
                          ^
TypeError: Class constructor SingleEntryDependency cannot be invoked without 'new'
```

https://github.com/webpack/webpack/commit/cd0109884520064ff155fde1fb7a895e73d1599e#diff-8d08712bab838c688cb6d414f73502dc

**Comment by vandy** [comment]
Webpack 3.x is supported in 3.x version.
